=== java-tools/awe/awe-boot/src/main/resources/schemas/awe/locale.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--
  ==============================================================================
  Definition
  ==============================================================================
  -->

  <xs:annotation>
    <xs:appinfo>AWE Local Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an AWE Local file must be structured
    </xs:documentation>
  </xs:annotation>

  <!--
  ==============================================================================
  Includes
  ==============================================================================
  -->

  <xs:include schemaLocation="general.xsd"/>

  <!--
  ==============================================================================
  Elements
  ==============================================================================
  -->

  <!-- Locals Element -->
  <xs:element name="locales" type="localsType">
    <xs:unique name="LocalNameUnique">
      <xs:selector xpath=".//locale" />
      <xs:field xpath="@name" />
    </xs:unique>
  </xs:element>

  <!-- Local Element -->
  <xs:element name="locale" type="localType"/>

  <!--
  ==============================================================================
  Type definitions
  ==============================================================================
  -->

  <!-- Locals Type -->
  <xs:complexType name="localsType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="locale"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Local Type -->
  <xs:complexType name="localType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== java-tools/awe/awe-framework/awe-modules/awe-notifier/src/main/resources/application/awe-notifier/locale/Locale-FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Document   : Locale-FR
  Description: Application Locales
-->

<!--$Id$-->

<locales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/locale.xsd">
  <locale name="BUTTON_SET_READ" value="Marquer comme lu"/>
  <locale name="BUTTON_SET_UNREAD" value="Marquer comme non lu"/>
  <locale name="BUTTON_SETTINGS" value="Paramètres"/>
  <locale name="BUTTON_SHOW_NOTIFICATIONS" value="Afficher notifications"/>
  <locale name="EMAIL_MESSAGE_HTML_NOTIFY" value="&lt;strong&gt;Sujet:&lt;/strong&gt; [#subscription#]&lt;br/&gt;&lt;br/&gt;&#xa;[#description#]&lt;br/&gt;"/>
  <locale name="EMAIL_MESSAGE_TEXT_NOTIFY" value="Sujet: [#subscription#]&#xa;&#xa;[#description#]"/>
  <locale name="EMAIL_SUBJECT_NOTIFY" value="[NOTIFICATION] [#title#]"/>
  <locale name="ENUM_NOTIFICATION_ERROR" value="Erreur"/>
  <locale name="ENUM_NOTIFICATION_INFO" value="Instructif"/>
  <locale name="ENUM_NOTIFICATION_NORMAL" value="Normal"/>
  <locale name="ENUM_NOTIFICATION_OK" value="Succès"/>
  <locale name="ENUM_NOTIFICATION_WARNING" value="Avertissement"/>
  <locale name="HELP_SET_READ" value="Marquer toutes les notifications sélectionnées comme lu"/>
  <locale name="HELP_SET_UNREAD" value="Marquer toutes les notifications sélectionnées comme non lu"/>
  <locale name="MENU_NOTIFIER" value="Déclarant"/>
  <locale name="MENU_NOTIFIER_NOTIFICATIONS" value="Notifications"/>
  <locale name="MENU_NOTIFIER_SUBSCRIPTIONS" value="Abonnements"/>
  <locale name="NO_NOTIFICATIONS" value="Pas de notifications"/>
  <locale name="PARAMETER_SUBSCRIPTION" value="Abonnement"/>
  <locale name="PARAMETER_UNREAD" value="Non lus"/>
  <locale name="SCREEN_HELP_NEW_SUBSCRIPTION" value="Ici, vous pouvez ajouter un nouvel abonnement"/>
  <locale name="SCREEN_HELP_NOTIFICATIONS" value="L&apos;écran du liste des notifications. Vous permet de consulter toutes les notifications et les marquer comme lu/non lu."/>
  <locale name="SCREEN_HELP_SUBSCRIPTIONS" value="Cette fenêtre gère la définition de souscription des sujets pour les notifications"/>
  <locale name="SCREEN_TEXT_EMAIL" value="E-mail"/>
  <locale name="SCREEN_TEXT_NOTIFICATIONS" value="Notifications"/>
  <locale name="SCREEN_TEXT_SUBSCRIPTION_DATA" value="Données d&apos;abonnement"/>
  <locale name="SCREEN_TEXT_SUBSCRIPTIONS" value="Abonnements"/>
  <locale name="SCREEN_TEXT_WEB" value="Web"/>
  <locale name="SCREEN_TITLE_NEW_SUBSCRIPTION" value="Nouvel abonnement"/>
  <locale name="SCREEN_TITLE_NOTIFICATIONS" value="Notifications"/>
  <locale name="SCREEN_TITLE_SETTINGS" value="Paramètres d&apos;utilisateur"/>
  <locale name="SCREEN_TITLE_SUBSCRIPTIONS" value="Abonnements"/>
</locales>

=== java-tools/awe/awe-tools/src/main/resources/application/awe-tools/locale/Locale-FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Document   : Locale-FR
  Description: Application Locales
-->

<!--$Id$-->

<locales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/locale.xsd">
  <locale name="BUTTON_LOAD" value="Charge"/>
  <locale name="BUTTON_SAVE" value="Enregistrer"/>
  <locale name="DATABASE_MESSAGE_RESPONSE_OK" value="L&apos;opération a été couronnée de succès"/>
  <locale name="DATABASE_MESSAGE_TITLE" value="Base de données de messages"/>
  <locale name="ERROR_MESSAGE_BUILD_COLUMNS" value="Erreur lors de la création des colonnes"/>
  <locale name="ERROR_MESSAGE_PERMISION_DENIED" value="Vous avez pas l&apos;autorisation d&apos;effectuer cette action"/>
  <locale name="ERROR_MESSAGE_PRINTING" value="Erreur lors de l&apos;impression"/>
  <locale name="ERROR_MESSAGE_SELECT_RUN" value="Échoué à exécuter l&apos;instruction SQL"/>
  <locale name="ERROR_MESSAGE_SESSION_EXPIRED" value="Votre connexion a expiré. Vous connecter à nouveau s&apos;il vous plaît."/>
  <locale name="ERROR_MESSAGE_SQL" value="Erreur Sql"/>
  <locale name="ERROR_MESSAGE_WRITING_SELECTS" value="Erreur lors de l&apos;écriture les clauses SELECT"/>
  <locale name="ERROR_TITLE_BUILD_COLUMNS" value="Erreur de colonne"/>
  <locale name="ERROR_TITLE_PRINTING" value="Erreur d&apos;impression"/>
  <locale name="ERROR_TITLE_SESSION_EXPIRED" value="Session expirée"/>
  <locale name="ERROR_TITLE_WRITING_SELECTS" value="Erreur SQL"/>
  <locale name="HELP_LOAD_BUTTON" value="Cliquez ici pour charger des instructions SQL à partir d&apos;un fichier"/>
  <locale name="HELP_SAVE_BUTTON" value="Cliquez ici pour enregistrer des instructions SQL dans un fichier"/>
  <locale name="MENU_FILE_MANAGER" value="Gestionnaire de fichiers"/>
  <locale name="PARAMETER_DATABASE" value="La base de données"/>
  <locale name="PARAMETER_FILE" value="Fichier"/>
  <locale name="PARAMETER_SAVE_FILE" value="Nom de fichier"/>
  <locale name="SCREEN_TITLE_LOAD_SELECT" value="Charge de sélectionner"/>
  <locale name="SCREEN_TITLE_SAVE_SELECT" value="Sélectionnez enregistrer"/>
  <locale name="SCREEN_TITLE_SQL_EXTRACTOR" value="SQL Extracteur"/>
  <locale name="WARNING_MESSAGE_DUPLICATED_FILE" value="Un fichier avec ce nom existe déjà. Voulez-vous le remplacer?"/>
  <locale name="WARNING_TITLE_DUPLICATED_FILE" value="Dupliqué"/>
</locales>

=== java-tools/awe/awe-developer/src/main/resources/application/awe-developer/locale/Locale-ES.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Document   : Locale-ES
  Description: Application Locales
-->

<!--$Id$-->

<locales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/locale.xsd">
  <locale name="BUTTON_TRANSLATE" value="Traducir"/>
  <locale name="COLUMN_CODE" value="Código"/>
  <locale name="COLUMN_LANGUAGE" value="Idioma"/>
  <locale name="COLUMN_LOCAL" value="Literal"/>
  <locale name="CONFIRM_MESSAGE_UPDATE_WRK_DIR" value="La ruta se ha almacenado correctamente"/>
  <locale name="CONFIRM_TITLE_UPDATE_WRK_DIR" value="Ruta actualizada correctamente"/>
  <locale name="ENUM_FORMAT_MARKDOWN" value="Markdown"/>
  <locale name="ENUM_FORMAT_TEXT" value="Texto"/>
  <locale name="ERROR_MESSAGE_UPDATE_WRK_DIR" value="La ruta no existe"/>
  <locale name="ERROR_TITLE_CLOSE_STREAM" value="Error de cierre del fichero"/>
  <locale name="ERROR_TITLE_RETRIEVING_TRANSLATION" value="Error al recuperar la traducción"/>
  <locale name="ERROR_TITLE_STORE_FILE" value="Error almacenando el archivo"/>
  <locale name="ERROR_TITLE_STORING_TRANSLATION" value="Error de almacenamiento de traducción"/>
  <locale name="ERROR_TITLE_UPDATE_WRK_DIR" value="Error al actualizar la ruta"/>
  <locale name="HELP_CLOSE_DIALOG_BUTTON" value="Cerrar el diálogo actual sin hacer nada"/>
  <locale name="HELP_SCREEN_MNG_PTH"><![CDATA[Esta pantalla permite al desarrollador para establecer la ruta de acceso de los ficheros XML de su proyecto, para trabajar con las herramientas de desarrollo.]]></locale>
  <locale name="HELP_SCREEN_TITLE_MNG_LIT"><![CDATA[En esta pantalla puede crear, eliminar o actualizar los textos de los idiomas de la aplicación]]></locale>
  <locale name="HELP_SWITCH_LANGUAGES_BUTTON"><![CDATA[Intercambia los valores de los selectores de idioma]]></locale>
  <locale name="HELP_TRANSLATE_BUTTON"><![CDATA[Traducir el valor del idioma de origen seleccionado al idioma de destino]]></locale>
  <locale name="OK_TITLE_LOCAL_UPDATED" value="Literal actualizado correctamente"/>
  <locale name="OK_TITLE_NEW_LOCAL" value="Nuevo literal generado"/>
  <locale name="OK_TITLE_REMOVED_LOCAL" value="Literal eliminado con éxito"/>
  <locale name="PARAMETER_IDENTIFIER" value="Identificador"/>
  <locale name="PARAMETER_LOCAL_VALUE" value="Valor"/>
  <locale name="PARAMETER_NEW_PATH" value="Nueva ruta de acceso"/>
  <locale name="PARAMETER_PATH" value="Ruta de acceso actual"/>
  <locale name="PARAMETER_SEARCH" value="Buscar"/>
  <locale name="SCREEN_TITLE_MNG_LIT" value="Gestor de literales"/>
  <locale name="SCREEN_TITLE_MNG_PTH" value="Gestor de ruta de desarrollo"/>
  <locale name="SCREEN_TITLE_NEW_LOCAL" value="Nuevo literal"/>
  <locale name="TITLE_LOCALS" value="Literales"/>
  <locale name="TITLE_PATH" value="Camino"/>
  <locale name="TITLE_SEARCH" value="Búsqueda"/>
  <locale name="TITLE_TRANSLATION" value="Traducción"/>
  <locale name="TITLE_TRANSLATIONS" value="Traducciones"/>
  <locale name="WARNING_MESSAGE_TRANSLATION_FAILED" value="No se pude conectar con la API de traducción"/>
  <locale name="WARNING_TITLE_NEW_LOCAL" value="Literal ya existente"/>
</locales>

=== java-tools/awe/awe-tools/src/main/resources/application/awe-tools/locale/Locale-EN.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Document   : Locale-EN
  Description: Application Locales
-->

<!--$Id$-->

<locales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://aweframework.gitlab.io/awe/docs/schemas/locale.xsd">
  <locale name="BUTTON_LOAD" value="Load"/>
  <locale name="BUTTON_SAVE" value="Save"/>
  <locale name="DATABASE_MESSAGE_RESPONSE_OK" value="The operation was completed successfully"/>
  <locale name="DATABASE_MESSAGE_TITLE" value="Database message"/>
  <locale name="ERROR_MESSAGE_BUILD_COLUMNS" value="Error while building the columns"/>
  <locale name="ERROR_MESSAGE_PERMISION_DENIED" value="You don&apos;t have permission to perform this action"/>
  <locale name="ERROR_MESSAGE_PRINTING" value="Error while printing"/>
  <locale name="ERROR_MESSAGE_SELECT_RUN" value="Failed to execute SQL statement"/>
  <locale name="ERROR_MESSAGE_SESSION_EXPIRED" value="Your connection has expired. You must login again."/>
  <locale name="ERROR_MESSAGE_SQL" value="SQL error"/>
  <locale name="ERROR_MESSAGE_WRITING_SELECTS" value="Error while writing SELECT clauses"/>
  <locale name="ERROR_TITLE_BUILD_COLUMNS" value="Column error"/>
  <locale name="ERROR_TITLE_PRINTING" value="Printing error"/>
  <locale name="ERROR_TITLE_SESSION_EXPIRED" value="Session expired"/>
  <locale name="ERROR_TITLE_WRITING_SELECTS" value="SQL error"/>
  <locale name="HELP_LOAD_BUTTON" value="Click here to load SQL statements from file"/>
  <locale name="HELP_SAVE_BUTTON" value="Click here to save SQL statements to a file"/>
  <locale name="MENU_FILE_MANAGER" value="File manager"/>
  <locale name="PARAMETER_DATABASE" value="Data base"/>
  <locale name="PARAMETER_FILE" value="File"/>
  <locale name="PARAMETER_SAVE_FILE" value="File name"/>
  <locale name="SCREEN_TITLE_LOAD_SELECT" value="Load query"/>
  <locale name="SCREEN_TITLE_SAVE_SELECT" value="Save query"/>
  <locale name="SCREEN_TITLE_SQL_EXTRACTOR" value="SQL Extractor"/>
  <locale name="WARNING_MESSAGE_DUPLICATED_FILE" value="A file with this name already exists. Do you want to replace it?"/>
  <locale name="WARNING_TITLE_DUPLICATED_FILE" value="Duplicated"/>
</locales>

=== java-tools/awe/awe-framework/awe-modules/awe-notifier/src/main/resources/application/awe-notifier/locale/Locale-EN.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Document   : Locale-EN
  Description: Application Locales
-->

<!--$Id$-->

<locales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/locale.xsd">
  <locale name="BUTTON_SET_READ" value="Mark read"/>
  <locale name="BUTTON_SET_UNREAD" value="Mark unread"/>
  <locale name="BUTTON_SETTINGS" value="Settings"/>
  <locale name="BUTTON_SHOW_NOTIFICATIONS" value="Show notifications"/>
  <locale name="EMAIL_MESSAGE_HTML_NOTIFY" value="&lt;strong&gt;Topic:&lt;/strong&gt; [#subscription#]&lt;br/&gt;&lt;br/&gt;&#xa;[#description#]&lt;br/&gt;"/>
  <locale name="EMAIL_MESSAGE_TEXT_NOTIFY" value="Topic: [#subscription#]&#xa;&#xa;[#description#]"/>
  <locale name="EMAIL_SUBJECT_NOTIFY" value="[NOTIFICATION] [#title#]"/>
  <locale name="ENUM_NOTIFICATION_ERROR" value="Error"/>
  <locale name="ENUM_NOTIFICATION_INFO" value="Informative"/>
  <locale name="ENUM_NOTIFICATION_NORMAL" value="Normal"/>
  <locale name="ENUM_NOTIFICATION_OK" value="Success"/>
  <locale name="ENUM_NOTIFICATION_WARNING" value="Warning"/>
  <locale name="HELP_SET_READ" value="Mark all selected notifications as read"/>
  <locale name="HELP_SET_UNREAD" value="Mark all selected notifications as unread"/>
  <locale name="MENU_NOTIFIER" value="Notifier"/>
  <locale name="MENU_NOTIFIER_NOTIFICATIONS" value="Notifications"/>
  <locale name="MENU_NOTIFIER_SUBSCRIPTIONS" value="Subscriptions"/>
  <locale name="NO_NOTIFICATIONS" value="No notifications"/>
  <locale name="PARAMETER_SUBSCRIPTION" value="Subscription"/>
  <locale name="PARAMETER_UNREAD" value="Unread"/>
  <locale name="SCREEN_HELP_NEW_SUBSCRIPTION" value="Here you can add a new subscription topic"/>
  <locale name="SCREEN_HELP_NOTIFICATIONS" value="Notification list screen. Allows you to view all notifications and mark them as read/unread."/>
  <locale name="SCREEN_HELP_SUBSCRIPTIONS" value="This window manages the definition of subscription topics for notifications"/>
  <locale name="SCREEN_TEXT_EMAIL" value="E-mail"/>
  <locale name="SCREEN_TEXT_NOTIFICATIONS" value="Notifications"/>
  <locale name="SCREEN_TEXT_SUBSCRIPTION_DATA" value="Subscription data"/>
  <locale name="SCREEN_TEXT_SUBSCRIPTIONS" value="Subscriptions"/>
  <locale name="SCREEN_TEXT_WEB" value="Web"/>
  <locale name="SCREEN_TITLE_NEW_SUBSCRIPTION" value="New subscription"/>
  <locale name="SCREEN_TITLE_NOTIFICATIONS" value="Notifications"/>
  <locale name="SCREEN_TITLE_SETTINGS" value="User settings"/>
  <locale name="SCREEN_TITLE_SUBSCRIPTIONS" value="Subscriptions"/>
</locales>

=== java-tools/awe/awe-developer/src/main/resources/application/awe-developer/locale/Locale-FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Document   : Locale-FR
  Description: Application Locales
-->

<!--$Id$-->

<locales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://aweframework.gitlab.io/awe/docs/schemas/locale.xsd">
  <locale name="BUTTON_TRANSLATE" value="Traduire"/>
  <locale name="COLUMN_CODE" value="Code"/>
  <locale name="COLUMN_LANGUAGE" value="Langue"/>
  <locale name="COLUMN_LOCAL" value="Littéral"/>
  <locale name="CONFIRM_MESSAGE_UPDATE_WRK_DIR" value="Le chemin de travail a été enregistré avec succès"/>
  <locale name="CONFIRM_TITLE_UPDATE_WRK_DIR" value="Chemin d&apos;accès de mise à jour avec succès"/>
  <locale name="ENUM_FORMAT_MARKDOWN" value="Markdown"/>
  <locale name="ENUM_FORMAT_TEXT" value="Texte"/>
  <locale name="ERROR_MESSAGE_UPDATE_WRK_DIR" value="Le chemin d&apos;accès n&apos;existe pas"/>
  <locale name="ERROR_TITLE_CLOSE_STREAM" value="Erreur à la fermeture du fichier"/>
  <locale name="ERROR_TITLE_RETRIEVING_TRANSLATION" value="Erreur lors de la récupération de traduction"/>
  <locale name="ERROR_TITLE_STORE_FILE" value="Erreur de stocker le fichier"/>
  <locale name="ERROR_TITLE_STORING_TRANSLATION" value="Erreur de stockage de traduction"/>
  <locale name="ERROR_TITLE_UPDATE_WRK_DIR" value="Erreur de mise à jour chemin"/>
  <locale name="HELP_CLOSE_DIALOG_BUTTON" value="Fermer le dialogue sans rien faire d&apos;autre chose"/>
  <locale name="HELP_SCREEN_MNG_PTH"><![CDATA[Cet écran permet au développeur de définir le chemin d'accès où sont les fichiers XML de votre projet, pour travailler avec les outils de développement]]></locale>
  <locale name="HELP_SCREEN_TITLE_MNG_LIT"><![CDATA[Dans cet écran, vous pouvez créer, supprimer ou mettre les textes des langues de l'application]]></locale>
  <locale name="HELP_SWITCH_LANGUAGES_BUTTON"><![CDATA[Basculer les valeurs des sélecteurs de langue]]></locale>
  <locale name="HELP_TRANSLATE_BUTTON"><![CDATA[Traduire la valeur de la langue source vers la langue cible sélectionnée]]></locale>
  <locale name="OK_TITLE_LOCAL_UPDATED" value="Paramètre régionaux mis à jour avec succès"/>
  <locale name="OK_TITLE_NEW_LOCAL" value="Nouvelle localee générée"/>
  <locale name="OK_TITLE_REMOVED_LOCAL" value="Locale supprimé avec succès"/>
  <locale name="PARAMETER_IDENTIFIER" value="Identificateur"/>
  <locale name="PARAMETER_LOCAL_VALUE" value="Valeur"/>
  <locale name="PARAMETER_NEW_PATH" value="Nouveau chemin"/>
  <locale name="PARAMETER_PATH" value="Chemin d&apos;accès actuel"/>
  <locale name="PARAMETER_SEARCH" value="Recherche"/>
  <locale name="SCREEN_TITLE_MNG_LIT" value="Gestion des paramètres régionaux"/>
  <locale name="SCREEN_TITLE_MNG_PTH" value="Le gestionnaire  de la route de développement"/>
  <locale name="SCREEN_TITLE_NEW_LOCAL" value="Nouveau paramètre régionaux"/>
  <locale name="TITLE_LOCALS" value="Littéraux"/>
  <locale name="TITLE_PATH" value="Chemin"/>
  <locale name="TITLE_SEARCH" value="Recherche"/>
  <locale name="TITLE_TRANSLATION" value="Traduction"/>
  <locale name="TITLE_TRANSLATIONS" value="Traductions"/>
  <locale name="WARNING_MESSAGE_TRANSLATION_FAILED" value="Impossible de se connecter avec l&apos;API de traduction"/>
  <locale name="WARNING_TITLE_NEW_LOCAL" value="Paramètres régionaux déjà existant"/>
</locales>
