=== java-tools/awe/awe-boot-archetype/src/main/resources/archetype-resources/src/main/resources/schemas/awe/services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--
  ==============================================================================
  Definition
  ==============================================================================
  -->

  <xs:annotation>
    <xs:appinfo>awe Services Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an awe Services file must be structured
    </xs:documentation>
  </xs:annotation>

  <!--
  ==============================================================================
  Includes
  ==============================================================================
  -->

  <xs:include schemaLocation="general.xsd"/>

  <!--
  ==============================================================================
  Elements
  ==============================================================================
  -->

  <!-- Services Element -->
  <xs:element name="services" type="servicesType">
    <xs:unique name="ServiceKey">
      <xs:selector xpath=".//service" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>

  <!-- Service Element -->
  <xs:element name="service" type="serviceType"/>

  <!-- Java Element -->
  <xs:element name="java" type="javaType"/>

  <!-- Microservice Element -->
  <xs:element name="microservice" type="microserviceType"/>

  <!-- Rest Element -->
  <xs:element name="rest" type="restType"/>

  <!-- Service Parameter Element -->
  <xs:element name="service-parameter" type="serviceParameterType"/>

  <!--
  ==============================================================================
  Type definitions
  ==============================================================================
  -->

  <!-- Services Type -->
  <xs:complexType name="servicesType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Service Type -->
  <xs:complexType name="serviceType">
    <xs:choice>
      <xs:element ref="java"/>
      <xs:element ref="microservice"/>
      <xs:element ref="rest"/>
    </xs:choice>
    <xs:attribute name="id" use="required" type="xs:string"/>
    <xs:attribute name="launch-phase" type="launchPhaseEnum"/>
  </xs:complexType>

  <!-- Java Type -->
  <xs:complexType name="javaType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="classname" use="required"/>
    <xs:attribute name="method" use="required" type="xs:string"/>
  </xs:complexType>

  <!-- Microservice Type -->
  <xs:complexType name="microserviceType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="endpoint" use="required" type="xs:string"/>
    <xs:attribute name="method" use="required" type="methodEnum"/>
    <xs:attribute name="wrapper" use="optional" type="xs:string"/>
    <xs:attribute name="content-type" use="optional" type="contentTypeEnum"/>
  </xs:complexType>

  <!-- Rest Type -->
  <xs:complexType name="restType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="server" use="optional" type="xs:string"/>
    <xs:attribute name="endpoint" use="required" type="xs:string"/>
    <xs:attribute name="method" use="required" type="methodEnum"/>
    <xs:attribute name="wrapper" use="optional" type="xs:string"/>
    <xs:attribute name="content-type" use="optional" type="contentTypeEnum"/>
  </xs:complexType>

  <!-- Jms Type -->
  <xs:complexType name="jmsType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="service-parameter"/>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="type" use="required" type="serviceTypeRestriction"/>
    <xs:attribute name="timeout" use="optional" type="xs:string"/>
    <xs:attribute name="cacheable" type="booleanEnum"/>
  </xs:complexType>

  <!-- Service Parameter Type -->
  <xs:complexType name="serviceParameterType">
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="type" use="required" type="serviceVariableRestriction"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="list" type="booleanEnum"/>
  </xs:complexType>

  <!-- Service Variable Restriction -->
  <xs:simpleType name="launchPhaseEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="APPLICATION_START"/>
      <xs:enumeration value="APPLICATION_END"/>
      <xs:enumeration value="CLIENT_START"/>
      <xs:enumeration value="CLIENT_END"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Service Method Restriction -->
  <xs:simpleType name="methodEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="GET"/>
      <xs:enumeration value="POST"/>
      <xs:enumeration value="PUT"/>
      <xs:enumeration value="DELETE"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Content type Restriction -->
  <xs:simpleType name="contentTypeEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="JSON"/>
      <xs:enumeration value="URLENCODED"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== java-tools/awe/awe-developer/src/main/resources/application/awe-developer/global/Services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--$Id$ -->
<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://aweframework.gitlab.io/awe/docs/schemas/services.xsd">
  <!-- dev -->
  <service id="LitTra">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="translate">
      <service-parameter name="text" type="STRING" />
      <service-parameter name="fromLanguage" type="STRING" />
      <service-parameter name="toLanguage" type="STRING" />
    </java>
  </service>
  <service id="LitLst">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="getLocaleMatches">
      <service-parameter name="literal" type="STRING" />
      <service-parameter name="language" type="STRING" />
    </java>
  </service>
  <service id="GetTraSer">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="getTranslationList">
      <service-parameter name="code" type="STRING" />
    </java>
  </service>
  <service id="LitSavSer">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="saveTranslation">
      <service-parameter name="formatSelector" type="STRING" />
      <service-parameter name="text" type="STRING" />
      <service-parameter name="markdown" type="STRING" />
      <service-parameter name="language" type="STRING" />
      <service-parameter name="searchLanguage" type="STRING" />
      <service-parameter name="code" type="STRING" />
    </java>
  </service>
  <service id="LitNewSer">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="newLiteral">
      <service-parameter name="language" type="STRING" />
      <service-parameter name="code" type="STRING" />
      <service-parameter name="literal" type="STRING" />
    </java>
  </service>
  <service id="LitDelSer">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="deleteLiteral">
      <service-parameter name="code" type="STRING" />
    </java>
  </service>
  <service id="LanSesVarSer">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="getUsingLanguage" />
  </service>
  <service id="GetSelectedLocale">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="getSelectedLocale">
      <service-parameter name="language" type="STRING" />
      <service-parameter name="code" type="STRING" />
    </java>
  </service>
  <service id="SwitchLanguages">
    <java classname="com.almis.awe.developer.service.LiteralsService"
      method="switchLanguages">
      <service-parameter name="fromLanguage" type="STRING" />
      <service-parameter name="toLanguage" type="STRING" />
      <service-parameter name="fromTarget" type="STRING" />
      <service-parameter name="toTarget" type="STRING" />
    </java>
  </service>

  <!-- Check Path -->
  <service id="checkPath">
    <java classname="com.almis.awe.developer.service.PathService"
      method="checkPath">
    </java>
  </service>
  <!-- Set Path -->
  <service id="SetPath">
    <java classname="com.almis.awe.developer.service.PathService"
      method="setPath">
      <service-parameter name="pathval" type="STRING" />
    </java>
  </service>
</services>

=== java-tools/awe/awe-framework/awe-modules/awe-tools/src/main/resources/application/awe-tools/global/Services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--$Id$-->
<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/services.xsd">

  <!-- Extract sql -->
  <service id="selectExtract">
    <java classname="com.almis.awe.tools.service.SqlExtractorService" method="extractData">
      <service-parameter name="select" type="STRING" />
      <service-parameter name="type" type="STRING" />
    </java>
  </service>
  <!-- Get Select File -->
  <service id="GetSelectFile">
    <java classname="com.almis.awe.tools.service.SqlExtractorService" method="getSelectFile">
    </java>
  </service>

  <!-- Load Select sentence -->
  <service id="loadSelect">
    <java classname="com.almis.awe.tools.service.SqlExtractorService" method="loadSelectSentence">
      <service-parameter name="fileName" type="STRING" />
    </java>
  </service>

  <!-- Save select file -->
  <service id="SaveSelectFile">
    <java classname="com.almis.awe.tools.service.SqlExtractorService" method="saveSelectFile">
      <service-parameter name="saveFileName" type="STRING" />
      <service-parameter name="selectsText" type="STRING" />
    </java>
  </service>

  <!-- Load Select sentence -->
  <service id="duplicatedFile">
    <java classname="com.almis.awe.tools.service.SqlExtractorService" method="checkFile">
      <service-parameter name="fileName" type="STRING" />
    </java>
  </service>

  <!-- Load Select sentence -->
  <service id="DelSqlCol">
    <java classname="com.almis.awe.tools.service.SqlExtractorService" method="deleteColumns">
    </java>
  </service>
  <service id="ExpFilSql">
    <java classname="com.almis.awe.tools.service.SqlExtractorService" method="printColumns">
      <service-parameter name="select" type="STRING" />
      <service-parameter name="formats" type="STRING" list="true" />
    </java>
  </service>

</services>

=== java-tools/awe/awe-framework/awe-modules/awe-notifier/src/main/resources/application/awe-notifier/global/Services.xml
<?xml version="1.0" encoding="UTF-8"?>

<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/services.xsd">

  <service id="notifications">
    <java classname="com.almis.awe.notifier.service.NotifierService" method="getNotifications"/>
  </service>

  <service id="toggle-web-subscription">
    <java classname="com.almis.awe.notifier.service.NotifierService" method="toggleWebSubscription">
      <service-parameter type="STRING" name="user"/>
      <service-parameter type="INTEGER" name="subscription"/>
    </java>
  </service>

  <service id="toggle-email-subscription">
    <java classname="com.almis.awe.notifier.service.NotifierService" method="toggleEmailSubscription">
      <service-parameter type="STRING" name="user"/>
      <service-parameter type="INTEGER" name="subscription"/>
    </java>
  </service>

  <service id="go-to-notification-screen">
    <java classname="com.almis.awe.notifier.service.NotifierService" method="goToNotificationScreen">
      <service-parameter type="INTEGER" name="notification"/>
    </java>
  </service>

</services>

=== java-tools/awe/awe-framework/awe-modules/awe-scheduler/src/main/resources/application/awe-scheduler/global/Services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--$Id$ -->
<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/services.xsd">

  <!-- SCHEDULER SERVICES -->

  <!-- scheduler tserviceices -->
  <service id="getSchedulerTaskList">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="getTaskList"/>
  </service>

  <service id="getTaskProgressStatus">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="getTaskProgressStatus">
      <service-parameter type="JSON" name="address"/>
    </java>
  </service>

  <service id="getTaskExecutionList">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="getTaskExecutionList">
      <service-parameter type="INTEGER" name="taskId"/>
    </java>
  </service>

  <service id="getExecutionsToPurge">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="getExecutionsToPurge">
      <service-parameter type="INTEGER" name="taskId"/>
      <service-parameter type="INTEGER" name="executions"/>
    </java>
  </service>

  <service id="pauseTask">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="pauseTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
    </java>
  </service>
  <service id="resumeTask">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="resumeTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
    </java>
  </service>
  <service id="executeTaskNow">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="executeTaskNow">
      <service-parameter name="taskIde" type="INTEGER"/>
    </java>
  </service>
  <service id="insertSchedulerTask">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="insertSchedulerTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
      <service-parameter name="SendStatus" type="INTEGER" list="true"/>
      <service-parameter name="SendDestination" type="INTEGER" list="true"/>
    </java>
  </service>
  <service id="updateSchedulerTask">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="updateSchedulerTask">
      <service-parameter name="IdeTsk" type="INTEGER"/>
      <service-parameter name="SendStatus" type="INTEGER" list="true"/>
      <service-parameter name="SendDestination" type="INTEGER" list="true"/>
    </java>
  </service>
  <service id="deleteSchedulerTask">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="deleteSchedulerTask">
      <service-parameter name="IdeTsk" type="INTEGER" list="true"/>
    </java>
  </service>

  <service id="updateExecutionTime">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="updateExecutionTime">
      <service-parameter name="taskId" type="INTEGER"/>
      <service-parameter name="taskExecution" type="INTEGER"/>
    </java>
  </service>

  <!-- Scheduler calenserviceices -->
  <service id="insertSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="insertSchedulerCalendar">
      <service-parameter name="calendarIde" type="INTEGER"/>
    </java>
  </service>
  <service id="updateSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="updateSchedulerCalendar">
      <service-parameter name="calendarIde" type="INTEGER"/>
    </java>
  </service>
  <service id="deleteSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="deleteSchedulerCalendar">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>
  <service id="checkTriggerContainsCalendar">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="checkCalendarExist">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>
  <service id="deactivateSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="deactivateCalendar">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>
  <service id="activateSchedulerCalendar">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="activateCalendar">
      <service-parameter name="calendarIde" type="INTEGER" list="true"/>
    </java>
  </service>

  <service id="loadMaintainVariables">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="loadMaintainVariables">
      <service-parameter name="maintainStr" type="STRING"/>
    </java>
  </service>

  <service id="nextExecutions">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="computeNextFiretimes">
      <service-parameter name="fireTimes" type="INTEGER"/>
    </java>
  </service>

  <!-- Year select/suggest service, returns the next 100 years -->
  <service id="yearSelectService">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="yearSelectService"/>
  </service>

  <service id="startScheduler" launch-phase="APPLICATION_START">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="start"/>
  </service>

  <service id="stopScheduler">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="stop"/>
  </service>

  <service id="restartScheduler">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="restart"/>
  </service>

  <service id="clearAndStop">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="clearAndStop"/>
  </service>

  <service id="currentlyExecutingJobs">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="currentlyExecutingJobs"/>
  </service>

  <service id="getConfiguredJobs">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="getConfiguredJobs"/>
  </service>

  <service id="getSchedulerMetadata">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="getSchedulerMetadata"/>
  </service>

  <service id="loadExecutionScreen">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="loadExecutionScreen">
      <service-parameter name="executionLogPath" type="STRING"/>
      <service-parameter name="address" type="JSON" />
    </java>
  </service>

  <service id="reloadExecutionScreen">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="reloadExecutionScreen">
      <service-parameter name="taskId" type="INTEGER"/>
      <service-parameter name="executionId" type="INTEGER" />
    </java>
  </service>

  <service id="purgeExecutionLogs">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="purgeExecutionLogs">
      <service-parameter name="taskId" type="INTEGER"/>
      <service-parameter name="executions" type="INTEGER" />
    </java>
  </service>

  <service id="purgeExecutionsAtStart" launch-phase="APPLICATION_START">
    <java classname="com.almis.awe.scheduler.service.SchedulerService" method="purgeExecutionsAtStart"/>
  </service>

</services>
