=== java-tools/awe/awe-framework/awe-generic-screens/src/main/resources/schemas/awe/queries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- ============================================================================== Definition ============================================================================== -->

  <xs:annotation>
    <xs:appinfo>awe Queries Schema</xs:appinfo>
    <xs:documentation xml:lang="en">
      This Schema defines the way an awe Queries file must be structured
    </xs:documentation>
  </xs:annotation>

  <!-- ============================================================================== Includes ============================================================================== -->

  <xs:include schemaLocation="query.xsd" />

  <!-- ============================================================================== Elements ============================================================================== -->

  <!-- Queries Element -->
  <xs:element name="queries" type="queriesType">
    <xs:unique name="QueryNameUnique">
      <xs:selector xpath=".//query" />
      <xs:field xpath="@id" />
    </xs:unique>
  </xs:element>

  <!-- Table Element -->
  <xs:element name="table" type="tableType" />

  <!-- Field Element -->
  <xs:element name="field" type="fieldType" />

  <!-- Constant Element -->
  <xs:element name="constant" type="constantType" />

  <!-- Case Element -->
  <xs:element name="operation" type="operationType" />

  <!-- Case Element -->
  <xs:element name="case" type="caseType" />

  <!-- Case When Element -->
  <xs:element name="when" type="caseWhenType" />

  <!-- Case Then Element -->
  <xs:element name="then" type="operandType" />

  <!-- Case Else Element -->
  <xs:element name="else" type="operandType" />

  <!-- Filter Element -->
  <xs:element name="filter" type="filterType"/>

  <!-- And Element -->
  <xs:element name="and" type="filterGroupType"/>

  <!-- Or Element -->
  <xs:element name="or" type="filterGroupType"/>

  <!-- Left operand element -->
  <xs:element name="left-operand" type="operandType" />

  <!-- Right operand element -->
  <xs:element name="right-operand" type="operandType" />

  <!-- Query Element -->
  <xs:element name="query" type="queryType" />

  <!-- Computed Element -->
  <xs:element name="computed" type="computedType" />

  <!-- Compound Element -->
  <xs:element name="compound" type="compoundType" />

  <!-- Where Element -->
  <xs:element name="where" type="whereType"/>

  <!-- Having Element -->
  <xs:element name="having" type="whereType"/>

  <!-- Join Element -->
  <xs:element name="join" type="joinType" />

  <!-- Union Element -->
  <xs:element name="union" type="unionType" />

  <!-- Group By Element -->
  <xs:element name="group-by" type="groupByType" />

  <!-- Order By Element -->
  <xs:element name="order-by" type="orderByType" />

  <!-- Totalize element -->
  <xs:element name="totalize" type="totalizeType" />

  <!-- Totalize By Element -->
  <xs:element name="totalize-by" type="totalizeElementType" />

  <!-- Totalize Field Element -->
  <xs:element name="totalize-field" type="totalizeElementType" />

  <!-- ============================================================================== Attribute Groups ============================================================================== -->

  <!-- Server Call Attributes -->
  <xs:attributeGroup name="orderAttr">
    <xs:attribute name="field" use="required" type="xs:string" />
    <xs:attribute name="table" type="xs:string" />
  </xs:attributeGroup>

  <!-- ============================================================================== Group definitions ============================================================================== -->

  <!-- Queries Group -->
  <xs:group name="queryGroup">
    <xs:choice>
      <xs:element ref="table" />
      <xs:element ref="computed" />
      <xs:element ref="compound" />
      <xs:element ref="field" />
      <xs:element ref="constant" />
      <xs:element ref="operation" />
      <xs:element ref="case" />
      <xs:element ref="join" />
      <xs:element ref="union" />
      <xs:element ref="variable" />
      <xs:element ref="where" />
      <xs:element ref="having" />
      <xs:element ref="order-by" />
      <xs:element ref="group-by" />
      <xs:element ref="totalize" />
    </xs:choice>
  </xs:group>

  <!-- ============================================================================== Type definitions ============================================================================== -->

  <!-- Queries Type -->
  <xs:complexType name="queriesType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="query" />
    </xs:sequence>
  </xs:complexType>

  <!-- Query Type -->
  <xs:complexType name="queryType">
    <xs:group ref="queryGroup" minOccurs="0" maxOccurs="unbounded" />
    <xs:attribute name="distinct" type="booleanEnum" />
    <xs:attribute name="enumerated" type="xs:string" />
    <xs:attribute name="id" use="required" type="xs:string" />
    <xs:attribute name="service" type="xs:string" />
    <xs:attribute name="queue" type="xs:string" />
    <xs:attribute name="cacheable" type="booleanEnum" />
    <xs:attribute name="managed-pagination" type="booleanEnum" />
    <xs:attribute name="public" type="booleanEnum" />
  </xs:complexType>

  <!-- Table Type -->
  <xs:complexType name="tableType">
    <xs:attributeGroup ref="tableQueryAttr" />
  </xs:complexType>

  <!-- Field Type -->
  <xs:complexType name="fieldType">
    <xs:attributeGroup ref="fieldQueryAttr"/>
  </xs:complexType>

  <!-- Operation type -->
  <xs:complexType name="operationType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="field" />
      <xs:element ref="constant" />
      <xs:element ref="operation" />
      <xs:element ref="case" />
    </xs:choice>
    <xs:attributeGroup ref="operationQueryAttr"/>
  </xs:complexType>

  <!-- Field Type -->
  <xs:complexType name="constantType">
    <xs:attributeGroup ref="constantQueryAttr" />
  </xs:complexType>

  <!-- Case Else type -->
  <xs:complexType name="caseType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="when" />
      <xs:element ref="else" />
    </xs:choice>
    <xs:attributeGroup ref="caseQueryAttr"/>
  </xs:complexType>

  <!-- Operand Type -->
  <xs:complexType name="operandType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="field" />
      <xs:element ref="constant" />
      <xs:element ref="operation" />
      <xs:element ref="case" />
      <xs:element ref="when" />
      <xs:element ref="else" />
    </xs:choice>
    <xs:attributeGroup ref="operandAttr"/>
  </xs:complexType>


  <!-- FilterGroup Type -->
  <xs:complexType name="filterGroupType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="filter"/>
      <xs:element ref="or"/>
      <xs:element ref="and"/>
    </xs:choice>
  </xs:complexType>

  <!-- Where Type -->
  <xs:complexType name="whereType">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element ref="or"/>
      <xs:element ref="and"/>
    </xs:choice>
  </xs:complexType>

  <!-- Compound type -->
  <xs:complexType name="compoundType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element ref="computed" />
    </xs:sequence>
    <xs:attribute name="alias" use="required" type="xs:string" />
  </xs:complexType>

  <!-- Computed Element -->
  <xs:complexType name="computedType">
    <xs:attribute name="alias" use="required" type="xs:string" />
    <xs:attribute name="format" use="required" />
    <xs:attribute name="eval" type="booleanEnum" />
    <xs:attribute name="nullValue" type="xs:string" />
    <xs:attribute name="transform" type="transformType" />
    <xs:attribute name="pattern" type="xs:string" />
    <xs:attribute name="translate" type="xs:string" />
    <xs:attribute name="label" type="xs:string" />
  </xs:complexType>

  <!-- Case Else type -->
  <xs:complexType name="caseElseType">
    <xs:attributeGroup ref="operandAttr"/>
  </xs:complexType>

  <!-- Case When type -->
  <xs:complexType name="caseWhenType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="left-operand" />
      <xs:element ref="right-operand" />
      <xs:element ref="then" />
    </xs:choice>
    <xs:attributeGroup ref="filterAttr"/>
  </xs:complexType>

  <!-- Filter Type -->
  <xs:complexType name="filterType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="left-operand" />
      <xs:element ref="right-operand" />
    </xs:choice>
    <xs:attributeGroup ref="filterAttr"/>
  </xs:complexType>

  <!-- Join Element -->
  <xs:complexType name="joinType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="table" />
      <xs:element ref="or" />
      <xs:element ref="and" />
    </xs:choice>
    <xs:attribute name="type" type="joinElementType" />
  </xs:complexType>

  <!-- Union Element -->
  <xs:complexType name="unionType">
    <xs:attribute name="query" use="required" type="xs:string" />
    <xs:attribute name="type" type="unionElementType" />
  </xs:complexType>

  <!-- Group By Element -->
  <xs:complexType name="groupByType">
    <xs:attributeGroup ref="orderAttr" />
  </xs:complexType>

  <!-- Order By Type -->
  <xs:complexType name="orderByType">
    <xs:attributeGroup ref="orderAttr" />
    <xs:attribute name="type" type="orderType" />
  </xs:complexType>

  <!-- Totalize Type -->
  <xs:complexType name="totalizeType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="totalize-by" />
      <xs:element ref="totalize-field" />
    </xs:choice>
    <xs:attribute name="function" use="required" type="aggregationFunctions" />
    <xs:attribute name="label" use="required" type="xs:string" />
    <xs:attribute name="field" use="required" type="xs:string" />
    <xs:attribute name="style" use="required" type="totalizeStyleType" />
  </xs:complexType>

  <!-- Totalize Element Type -->
  <xs:complexType name="totalizeElementType">
    <xs:attribute name="field" use="required" type="xs:string" />
  </xs:complexType>

  <!-- =================================== Restriction definitions ========================================= -->

  <!-- Totalize Style Enumeration -->
  <xs:simpleType name="totalizeStyleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOTAL" />
      <xs:enumeration value="SUBTOTAL" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Order Type Enumeration -->
  <xs:simpleType name="orderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ASC" />
      <xs:enumeration value="DESC" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Join Type Enumeration -->
  <xs:simpleType name="joinElementType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FULL" />
      <xs:enumeration value="INNER" />
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="RIGHT" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Union Type Enumeration -->
  <xs:simpleType name="unionElementType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ALL" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== java-tools/awe/awe-framework/awe-modules/awe-notifier/src/main/resources/application/awe-notifier/global/Queries.xml
<?xml version="1.0" encoding="UTF-8"?>

<queries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://aweframework.gitlab.io/awe/docs/schemas/queries.xsd">

  <query id="notifications" service="notifications"/>
  <query id="user-notifications">
    <table id="AweNot" alias="notifications"/>
    <field id="Ide" table="notifications" alias="value"/>
    <field id="Nom" table="notifications" alias="title"/>
    <field id="Des" table="notifications" alias="description"/>
    <field id="Dat" table="notifications" alias="date" transform="DATE_SINCE"/>
    <field id="Ico" table="notifications" alias="icon"/>
    <field id="Typ" table="notifications" alias="type" translate="notification-type"/>
    <field id="Scr" table="notifications" alias="screen"/>
    <field id="Cod" table="notifications" alias="code"/>
    <join>
      <table id="ope" alias="users"/>
      <and>
        <filter left-field="l1_nom" left-table="users" condition="eq" right-variable="user" ignorecase="true"/>
      </and>
    </join>
    <join type="LEFT">
      <table id="AweNotUsr" alias="userNotifications"/>
      <and>
        <filter left-field="IdeOpe" left-table="userNotifications" condition="eq" right-field="IdeOpe" right-table="users"/>
        <filter left-field="IdeNot" left-table="userNotifications" condition="eq" right-field="Ide" right-table="notifications"/>
      </and>
    </join>
    <join>
      <table id="AweSub" alias="subscriptions"/>
      <and>
        <filter left-field="Ide" left-table="subscriptions" condition="eq" right-field="IdeSub"
                right-table="notifications"/>
      </and>
    </join>
    <join>
      <table id="AweSubUsr" alias="userSubscriptions"/>
      <and>
        <filter left-field="IdeOpe" left-table="userSubscriptions" condition="eq" right-field="IdeOpe" right-table="users"/>
        <filter left-field="IdeSub" left-table="userSubscriptions" condition="eq" right-field="IdeSub" right-table="notifications"/>
        <filter left-field="SubNot" left-table="userSubscriptions" condition="eq"><right-operand><constant value="1" type="INTEGER"/></right-operand></filter>
      </and>
    </join>
    <where>
      <and>
        <filter condition="eq" right-variable="unread" optional="true">
          <left-operand>
            <operation operator="COALESCE">
              <field id="Unr" table="userNotifications"/>
              <constant type="INTEGER" value="1"/>
            </operation>
          </left-operand>
        </filter>
      </and>
    </where>
    <order-by field="Dat" table="notifications" type="DESC"/>
    <variable id="user" type="STRING" session="user"/>
    <variable id="unread" type="INTEGER" value="1"/>
  </query>

  <query id="get-interested-users" distinct="true">
    <table id="ope" alias="users"/>
    <field id="l1_nom" alias="user"/>
    <field id="SubNot" alias="byWeb" transform="BOOLEAN"/>
    <field id="SubEma" alias="byEmail" transform="BOOLEAN"/>
    <join>
      <table id="AweSubUsr" alias="userSubscriptions"/>
      <and>
        <filter left-field="IdeOpe" left-table="userSubscriptions" condition="eq" right-field="IdeOpe" right-table="users"/>
      </and>
    </join>
    <join>
      <table id="AweSub" alias="subscriptions"/>
      <and>
        <filter left-field="Acr" left-table="subscriptions" condition="eq" right-variable="subscription"/>
        <filter left-field="Ide" left-table="subscriptions" condition="eq" right-field="IdeSub" right-table="userSubscriptions"/>
      </and>
    </join>
    <variable id="subscription" type="STRING" name="subscription"/>
  </query>

  <query id="notification-list">
    <table id="AweNot" alias="notifications"/>
    <field id="Ide" table="notifications" alias="id"/>
    <field id="Nom" table="notifications" alias="notification-name"/>
    <field id="Des" table="notifications" alias="notification-description"/>
    <field id="Scr" table="notifications" alias="notification-screen"/>
    <field id="Cod" table="notifications" alias="notification-code"/>
    <field id="Dat" table="notifications" alias="notification-date" transform="TIMESTAMP"/>
    <field id="Ico" table="notifications" alias="icon"/>
    <operation alias="unreadSort" operator="COALESCE">
      <field id="Unr" table="userNotifications"/>
      <constant type="INTEGER" value="1"/>
    </operation>
    <field id="Typ" table="notifications" alias="typeSort"/>
    <compound alias="notification-icon">
      <computed format="[typeSort]" alias="value"/>
      <computed format="fa-[icon] fa-inverse fa-border icon-fixed-width-grid" alias="icon"/>
      <computed format="[typeSort]" alias="style" translate="notification-style"/>
      <computed format="[typeSort]" alias="title" translate="notification-label"/>
      <computed format="" alias="label"/>
    </compound>
    <compound alias="notification-read">
      <computed format="[unreadSort]" alias="value"/>
      <computed format="[unreadSort]" alias="icon" translate="notification-read-icon"/>
      <computed format="[unreadSort]" alias="style" translate="notification-read-style"/>
      <computed format="[unreadSort]" alias="title" translate="notification-read-label"/>
    </compound>
    <computed alias="_style_" format="[unreadSort]" translate="unread-style"/>
    <join>
      <table id="ope" alias="users"/>
      <and>
        <filter left-field="l1_nom" left-table="users" condition="eq" right-variable="user" ignorecase="true"/>
      </and>
    </join>
    <join type="LEFT">
      <table id="AweNotUsr" alias="userNotifications"/>
      <and>
        <filter left-field="IdeOpe" left-table="userNotifications" condition="eq" right-field="IdeOpe" right-table="users"/>
        <filter left-field="IdeNot" left-table="userNotifications" condition="eq" right-field="Ide" right-table="notifications"/>
      </and>
    </join>
    <join>
      <table id="AweSub" alias="subscriptions"/>
      <and>
        <filter left-field="Ide" left-table="subscriptions" condition="eq" right-field="IdeSub" right-table="notifications"/>
      </and>
    </join>
    <join>
      <table id="AweSubUsr" alias="userSubscriptions"/>
      <and>
        <filter left-field="IdeOpe" left-table="userSubscriptions" condition="eq" right-field="IdeOpe" right-table="users"/>
        <filter left-field="IdeSub" left-table="userSubscriptions" condition="eq" right-field="IdeSub" right-table="notifications"/>
      </and>
    </join>
    <where>
      <and>
        <filter left-field="IdeSub" left-table="notifications" condition="eq" right-variable="subscription" optional="true"/>
        <filter left-field="Typ" left-table="notifications" condition="eq" right-variable="type" optional="true"/>
        <filter condition="eq" right-variable="unread" optional="true">
          <left-operand>
            <operation operator="COALESCE">
              <field id="Unr" table="userNotifications"/>
              <constant type="INTEGER" value="1"/>
            </operation>
          </left-operand>
        </filter>
        <or>
          <filter left-field="Nom" left-table="notifications" condition="like" right-variable="search" optional="true" ignorecase="true"/>
          <filter left-field="Des" left-table="notifications" condition="like" right-variable="search" optional="true" ignorecase="true"/>
        </or>
      </and>
    </where>
    <order-by field="Dat" table="notifications" type="DESC"/>
    <variable id="user" type="STRING" session="user"/>
    <variable id="unread" type="INTEGER" name="unread"/>
    <variable id="type" type="STRING" name="type"/>
    <variable id="subscription" type="INTEGER" name="subscription"/>
    <variable id="search" type="STRINGB" name="search"/>
  </query>

  <query id="subscription-suggest">
    <table id="AweSub" alias="subscriptions"/>
    <field id="Ide" table="subscriptions" alias="value"/>
    <field id="Nom" table="subscriptions" alias="label"/>
    <where>
      <or>
        <filter left-field="Acr" left-table="subscriptions" condition="like" right-variable="search" optional="true" ignorecase="true"/>
        <filter left-field="Nom" left-table="subscriptions" condition="like" right-variable="search" optional="true" ignorecase="true"/>
        <filter left-field="Des" left-table="subscriptions" condition="like" right-variable="search" optional="true" ignorecase="true"/>
      </or>
    </where>
    <variable id="search" type="STRINGB" name="suggest"/>
  </query>

  <query id="subscription-acronym">
    <table id="AweSub" alias="subscriptions"/>
    <field id="Ide" table="subscriptions" alias="value"/>
    <where>
      <and>
        <filter left-field="Acr" left-table="subscriptions" condition="eq" right-variable="acronym" ignorecase="true"/>
      </and>
    </where>
    <variable id="acronym" type="STRING" name="subscription"/>
  </query>

  <query id="check-subscription">
    <table id="AweSub" alias="subscriptions"/>
    <field id="Ide" table="subscriptions" alias="value"/>
    <where>
      <and>
        <filter left-field="Acr" left-table="subscriptions" condition="eq" right-variable="acronym" ignorecase="true"/>
        <filter left-field="Ide" left-table="subscriptions" condition="ne" right-variable="id" optional="true"/>
      </and>
    </where>
    <variable id="acronym" type="STRING" name="acronym"/>
    <variable id="id" type="INTEGER" name="id"/>
  </query>

  <query id="user-acronym">
    <table id="ope" alias="users"/>
    <field id="IdeOpe" table="users" alias="value"/>
    <where>
      <and>
        <filter left-field="l1_nom" left-table="users" condition="eq" right-variable="user" ignorecase="true"/>
      </and>
    </where>
    <variable id="user" type="STRING" session="user"/>
  </query>

  <query id="subscription-list">
    <table id="AweSub" alias="subscriptions"/>
    <field id="Ide" table="subscriptions" alias="id"/>
    <field id="Acr" table="subscriptions" alias="subscription-acronym"/>
